<?php
/**
 * Site Configuration — A-1 Roof Works LLC
 * Generated by Phase 1 scaffold.
 *
 * Fields marked [REQUIRED] must be filled with real client data before the site goes live.
 * Fields marked [OPTIONAL] may be left blank if not applicable.
 */

// ─── Business Identity ─────────────────────────────────────────────────────
$siteName        = 'A-1 Roof Works LLC';           // [REQUIRED] exact GBP name
$tagline         = 'Your Roof Done Right — The First Time';  // [REQUIRED]
$industry        = 'roofing';

// ─── Contact ───────────────────────────────────────────────────────────────
$phone           = '';           // [REQUIRED] format: (NXX) NXX-XXXX — must match GBP listing exactly
$phoneSecondary  = '';           // [OPTIONAL]
$email           = '';           // [REQUIRED] e.g. info@a1roofworks.com
$contactPhone    = $phone;       // alias used by legal-compliance templates
$contactEmail    = $email;       // alias used by legal-compliance templates

// ─── Address ───────────────────────────────────────────────────────────────
$addressStreet   = '';           // [REQUIRED] e.g. 123 Main St
$addressCity     = '';           // [REQUIRED] e.g. Springfield
$addressState    = '';           // [REQUIRED] e.g. IL
$addressZip      = '';           // [REQUIRED] e.g. 62701
$businessAddress = $addressStreet . ', ' . $addressCity . ', ' . $addressState . ' ' . $addressZip;

// Structured address array (for schema / templates)
$address = [
    'street' => $addressStreet,
    'city'   => $addressCity,
    'state'  => $addressState,
    'zip'    => $addressZip,
];

// ─── Domain / URLs ─────────────────────────────────────────────────────────
$domain          = 'a-1-roof-works-llc.pageone.cloud'; // placeholder — update before go-live
$siteUrl         = 'https://' . $domain;
$clientSlug      = 'a-1-roof-works-llc';

// ─── SEO Keywords ──────────────────────────────────────────────────────────
$primaryKeyword  = '';           // [REQUIRED] e.g. "roofing contractor springfield il"

$secondaryKeywords = [
    // [REQUIRED] add 8-12 secondary keywords
    // e.g. 'roof repair springfield il',
    // e.g. 'roof replacement springfield',
    // e.g. 'emergency roof repair',
    // e.g. 'storm damage roof repair',
    // e.g. 'asphalt shingle roofing',
    // e.g. 'metal roofing springfield',
    // e.g. 'residential roofing contractor',
    // e.g. 'roof inspection springfield il',
];

// ─── Services ──────────────────────────────────────────────────────────────
$services = [
    // [REQUIRED] populate from build-plan.json
    // Each entry: ['name' => '', 'description' => '', 'keywords' => []]
    //
    // Example:
    // [
    //     'name'        => 'Roof Replacement',
    //     'description' => 'Complete roof replacement with premium materials...',
    //     'keywords'    => ['roof replacement springfield il', 'new roof installation'],
    // ],
];

// ─── Service Areas ─────────────────────────────────────────────────────────
$serviceAreas = [
    // [REQUIRED] populate from build-plan.json
    // Each entry: ['city' => '', 'state' => '', 'zip' => '', 'primary' => false]
    //
    // Example (primary city first):
    // ['city' => 'Springfield', 'state' => 'IL', 'zip' => '62701', 'primary' => true],
    // ['city' => 'Decatur',     'state' => 'IL', 'zip' => '62521', 'primary' => false],
];

// ─── Social Links ──────────────────────────────────────────────────────────
$socialLinks = [
    // [OPTIONAL] add applicable platforms
    // 'facebook'  => '',
    // 'instagram' => '',
    // 'google'    => '',   // Google Business Profile URL
    // 'yelp'      => '',
    // 'bbb'       => '',
];

// ─── Analytics / Verification ──────────────────────────────────────────────
$ga4MeasurementId = '';   // [OPTIONAL] Google Analytics 4 Measurement ID
$gscVerification  = '';   // [OPTIONAL] Google Search Console meta content value

// ─── Business Details ──────────────────────────────────────────────────────
$yearEstablished  = '';   // [REQUIRED] e.g. 2005
$yearsInBusiness  = '';   // [REQUIRED] e.g. 20  (or compute: date('Y') - $yearEstablished)
$ownerName        = '';   // [OPTIONAL] owner's full name

// ─── Design / Brand Colors ─────────────────────────────────────────────────
$colors = [
    // [REQUIRED] set from logo analysis
    'primary'   => '',   // e.g. #1a2b3c
    'secondary' => '',   // e.g. #2d6a9f
    'accent'    => '',   // e.g. #f59e0b
];

// ─── Legal / Compliance ────────────────────────────────────────────────────
$entityType       = 'Limited Liability Company';   // [REQUIRED] matches legal filing
$stateOfFormation = $addressState;                  // defaults to operating state

// ─── Form Action ───────────────────────────────────────────────────────────
$formAction = 'https://db.pageone.cloud/functions/v1/leads/' . $clientSlug;
// [REQUIRED] — Page One CRM lead endpoint (do not change)

// ─── Tier ──────────────────────────────────────────────────────────────────
$tier = 'standard';   // [REQUIRED] basic | standard | premium

// ─── Reviews ───────────────────────────────────────────────────────────────
$googleReviews = [
    // [OPTIONAL] populate from client GBP if reviews are available
    // Each entry: ['author' => '', 'rating' => 5, 'text' => '', 'date' => '']
];
$aggregateRating     = '';   // [OPTIONAL] e.g. 4.9
$aggregateRatingCount = '';  // [OPTIONAL] e.g. 84

// ─── Google Business Profile ───────────────────────────────────────────────
$googleBusinessProfileUrl = '';   // [OPTIONAL]

// ─── Lead Notification ─────────────────────────────────────────────────────
$leadNotificationEmail = '';   // [OPTIONAL] where new leads are forwarded
$leadNotificationPhone = '';   // [OPTIONAL]
$leadsFormSecret = 'bac7714a8f41505ab12d75311ccbb11a6374e38b1a010d69111c84a652cfa0f3'; // spam-shield HMAC (matches leads fn LEADS_FORM_SECRET)
